# Convert relevant data from JSON to CSV file

The following code is for the Author-Keywords and Subject-Areas of BioInformatics Papers.

NOTE: I used the following code for all 6 JSON files, changing only the file name in notebook 1 (JSON input) and notebook 12 (CSV output)

In [1]:
# Load json file

import json
import pandas

json_data = open(r'/Users/loganhornbuckle/Documents/Python/DataScience/raw_json_full/good/scopus1986-2007.json').read()
data = json.loads(json_data)

In [2]:
print(data)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [3]:
# append eid to eid list

eid = []

for x in range (len(data)):
    if 'abstracts-retrieval-response' in data[x].keys():
        if 'coredata' in data[x]['abstracts-retrieval-response'].keys():
            if (data[x]['abstracts-retrieval-response']['coredata']) == None:
                eid.append("NaN")
            else:
                eid.append(data[x]['abstracts-retrieval-response']['coredata']['eid'])
    else:
        eid.append("NaN")

In [4]:
# append author-keyword keys to keyword list

keyword = []

for x in range (len(data)):
    if 'abstracts-retrieval-response' in data[x].keys():
        if ('authkeywords' in data[x]['abstracts-retrieval-response'].keys()):
            if (data[x]['abstracts-retrieval-response']['authkeywords']) == None:
                keyword.append("NaN")
            else:
                keyword.append(data[x]['abstracts-retrieval-response']['authkeywords']['author-keyword'])
    else:
        keyword.append("NaN")

In [5]:
# append subject keys to list subject

subAbbrev = []
subCode = []
subText = []
                
# append subkeys of subject: @abbrev, @code, and #text to seperate lists
for x in range (len(data)):
    if 'abstracts-retrieval-response' in data[x].keys():
        if data[x]['abstracts-retrieval-response']['subject-areas'] == None:
            subAbbrev.append("NaN")
            subCode.append("NaN")
            subText.append("NaN")
        else:
            if type(data[x]['abstracts-retrieval-response']['subject-areas']['subject-area']) is list:
                for i in range(len(data[x]['abstracts-retrieval-response']['subject-areas']['subject-area'])):
                    subAbbrev.append(data[x]['abstracts-retrieval-response']['subject-areas']['subject-area'][i]['@abbrev'])
                    subCode.append(data[x]['abstracts-retrieval-response']['subject-areas']['subject-area'][i]['@code'])
                    subText.append(data[x]['abstracts-retrieval-response']['subject-areas']['subject-area'][i]['#text'])
            else:
                subAbbrev.append(data[x]['abstracts-retrieval-response']['subject-areas']['subject-area']['@abbrev'])
                subCode.append(data[x]['abstracts-retrieval-response']['subject-areas']['subject-area']['@code'])
                subText.append(data[x]['abstracts-retrieval-response']['subject-areas']['subject-area']['#text'])
    else:
        subAbbrev.append("NaN")
        subCode.append("NaN")
        subText.append("NaN")

In [6]:
# print length of lists to check for errors

print("keyword length: " , len(keyword))
print("text length: " , len(subText))
print("abbrev length: " , len(subAbbrev))
print("code length: " , len(subCode))
print("eid length: " , len(eid))

keyword length:  18646
text length:  42399
abbrev length:  42399
code length:  42399
eid length:  18646

In [7]:
# crate dataFrame
df = pandas.DataFrame()

#Create column for Author Keyword
df["Author Keyword"] = keyword
df[:5]

                                      Author Keyword
0  [Computational biology, Neurodegenerative dise...
1  [Biodiversity, Biological resource centre, Cya...
2                                                NaN
3                                                NaN
4                                                NaN

In [8]:
# Create column for eid


for n in range (len(eid)):
    df["eID"] = eid[n]

for n in range (len(eid)):
    df["eID"][n] = eid[n]

df[:5]

                                      Author Keyword                 eID
0  [Computational biology, Neurodegenerative dise...  2-s2.0-38049161948
1  [Biodiversity, Biological resource centre, Cya...  2-s2.0-36749042030
2                                                NaN  2-s2.0-84858487958
3                                                NaN  2-s2.0-84858511527
4                                                NaN  2-s2.0-84858503835

In [9]:
# Create column for Subject Area: Abbreviation


for n in range (len(subAbbrev)):
    df["Abbreviation"] = subAbbrev[n]

for n in range (len(subAbbrev)):
    df["Abbreviation"][n] = subAbbrev[n]

df[:5]

,Author Keyword,eID,Abbreviation
0,"[Computational biology, Neurodegenerative dise...",2-s2.0-38049161948,BIOC
1,"[Biodiversity, Biological resource centre, Cya...",2-s2.0-36749042030,BIOC
2,NaN,2-s2.0-84858487958,BIOC
3,NaN,2-s2.0-84858511527,ENGI
4,NaN,2-s2.0-84858503835,ENGI

In [10]:
# Create column for Subject Area: Code

for n in range(len(subCode)):
    df["Code"] = subCode[n]

for n in range(len(subCode)):
    df["Code"][n] = subCode[n]

df[:5]

,Author Keyword,eID,Abbreviation,Code
0,"[Computational biology, Neurodegenerative dise...",2-s2.0-38049161948,BIOC,1303
1,"[Biodiversity, Biological resource centre, Cya...",2-s2.0-36749042030,BIOC,1311
2,NaN,2-s2.0-84858487958,BIOC,1311
3,NaN,2-s2.0-84858511527,ENGI,2200
4,NaN,2-s2.0-84858503835,ENGI,2200

In [11]:
# Create column for Subject Area: Text

for n in range(len(subText)):
    df["Text"] = subText[n]
    
for n in range(len(subText)):
    df["Text"][n] = subText[n]

df[:5]

,Author Keyword,eID,Abbreviation,Code,Text
0,"[Computational biology, Neurodegenerative dise...",2-s2.0-38049161948,BIOC,1303,Biochemistry
1,"[Biodiversity, Biological resource centre, Cya...",2-s2.0-36749042030,BIOC,1311,Genetics
2,NaN,2-s2.0-84858487958,BIOC,1311,Genetics
3,NaN,2-s2.0-84858511527,ENGI,2200,Engineering (all)
4,NaN,2-s2.0-84858503835,ENGI,2200,Engineering (all)

In [12]:
# preview data frame

df[:100]

,Author Keyword,eID,Abbreviation,Code,Text
0,"[Computational biology, Neurodegenerative dise...",2-s2.0-38049161948,BIOC,1303,Biochemistry
1,"[Biodiversity, Biological resource centre, Cya...",2-s2.0-36749042030,BIOC,1311,Genetics
2,NaN,2-s2.0-84858487958,BIOC,1311,Genetics
3,NaN,2-s2.0-84858511527,ENGI,2200,Engineering (all)
4,NaN,2-s2.0-84858503835,ENGI,2200,Engineering (all)
5,"[Bioinformatics tool, Comparative genomic hybr...",2-s2.0-37349108551,ENGI,2200,Engineering (all)
6,"[Ab initio prediction, Molecular dynamics simu...",2-s2.0-37349041400,BIOC,1311,Genetics
7,"[Bioinformatics, Flagellar motility, Genome sc...",2-s2.0-37349014523,BIOC,1311,Genetics
8,NaN,2-s2.0-84858512072,BIOC,1311,Genetics
9,"[ECG signal processing, Heart monitoring, Mobi...",2-s2.0-37349065612,ENGI,2200,Engineering (all)
10,NaN,2-s2.0-37349042217,BIOC,1300,"Biochemistry, Genetics and Molecular Biology (..."
11,"[Effector component, Lectin pathway, Promoter]",2-s2.0-36048947403,COMP,1700,Computer Science (all)
12,"[3-D modeling, Bioinformatics, Capsule endosco...",2-s2.0-37349030190,MATH,2614,Theoretical Computer Science
13,"[Bioinformatics, Latent semantic indexing, Mol...",2-s2.0-37349084966,BIOC,1311,Genetics
14,NaN,2-s2.0-37349039010,BIOC,1303,Biochemistry
15,NaN,2-s2.0-84858483521,BIOC,1304,Biophysics
16,"[Discretization, Gene expression data, Reducts...",2-s2.0-37349071519,BIOC,1312,Molecular Biology
17,NaN,2-s2.0-84988591378,COMP,1700,Computer Science (all)
18,NaN,2-s2.0-41049089044,BIOC,1300,"Biochemistry, Genetics and Molecular Biology (..."
19,NaN,2-s2.0-37349127372,MATH,2614,Theoretical Computer Science
20,"[Astrocytoma, Proteomics, Rat]",2-s2.0-40549117909,BIOC,1312,Molecular Biology
21,"[Critical residue, Gentisate 1,2-dioxygenase, ...",2-s2.0-38749134080,BIOC,1311,Genetics
22,NaN,2-s2.0-37249048033,AGRI,1100,Agricultural and Biological Sciences (all)
23,NaN,2-s2.0-37249038031,AGRI,1101,Agricultural and Biological Sciences (miscella...
24,NaN,2-s2.0-37249001273,ENGI,2200,Engineering (all)
25,NaN,2-s2.0-37249067061,MATH,2614,Theoretical Computer Science
26,NaN,2-s2.0-37249032559,COMP,1700,Computer Science (all)
27,NaN,2-s2.0-37249090728,AGRI,1100,Agricultural and Biological Sciences (all)
28,NaN,2-s2.0-37249035119,BIOC,1300,"Biochemistry, Genetics and Molecular Biology (..."
29,NaN,2-s2.0-37249020943,MEDI,2700,Medicine (all)
...,...,...,...,...,...
70,NaN,2-s2.0-37249011265,BIOC,1300,"Biochemistry, Genetics and Molecular Biology (..."
71,"[Adaptive control, Artificial immune systems, ...",2-s2.0-37249042751,MATH,2614,Theoretical Computer Science
72,NaN,2-s2.0-37249012841,COMP,1700,Computer Science (all)
73,NaN,2-s2.0-37249047123,BIOC,1300,"Biochemistry, Genetics and Molecular Biology (..."
74,NaN,2-s2.0-37249026752,MATH,2614,Theoretical Computer Science
75,NaN,2-s2.0-37249019523,COMP,1700,Computer Science (all)
76,NaN,2-s2.0-84954348756,BIOC,1300,"Biochemistry, Genetics and Molecular Biology (..."
77,"[γ-Turn types, Support vector machines (SVMs),...",2-s2.0-36248961670,MATH,2614,Theoretical Computer Science
78,NaN,2-s2.0-42149134851,BIOC,1300,"Biochemistry, Genetics and Molecular Biology (..."
79,NaN,2-s2.0-48149107668,COMP,1700,Computer Science (all)
80,NaN,2-s2.0-42149187635,MATH,2614,Theoretical Computer Science
81,NaN,2-s2.0-38849207456,COMP,1700,Computer Science (all)
82,NaN,2-s2.0-42149156031,BIOC,1300,"Biochemistry, Genetics and Molecular Biology (..."
83,NaN,2-s2.0-42149105642,MATH,2614,Theoretical Computer Science
84,NaN,2-s2.0-37149039636,COMP,1700,Computer Science (all)
85,NaN,2-s2.0-37149003143,BIOC,1300,"Biochemistry, Genetics and Molecular Biology (..."
86,NaN,2-s2.0-37149016806,MATH,2614,Theoretical Computer Science
87,NaN,2-s2.0-37149019919,MATH,2614,Theoretical Computer Science
88,NaN,2-s2.0-37149015538,COMP,1700,Computer Science (all)
89,NaN,2-s2.0-37149042345,COMP,1700,Computer Science (all)
90,NaN,2-s2.0-37149006746,BIOC,1300,"Biochemistry, Genetics and Molecular Biology (..."
91,NaN,2-s2.0-37149026778,MATH,2614,Theoretical Computer Science
92,NaN,2-s2.0-37149026044,COMP,1700,Computer Science (all)
93,NaN,2-s2.0-37149025058,BIOC,1300,"Biochemistry, Genetics and Molecular Biology (..."
94,NaN,2-s2.0-37149019373,MATH,2614,Theoretical Computer Science
95,NaN,2-s2.0-37149022969,COMP,1700,Computer Science (all)
96,NaN,2-s2.0-37149034099,BIOC,1300,"Biochemistry, Genetics and Molecular Biology (..."
97,NaN,2-s2.0-37149047907,MATH,2614,Theoretical Computer Science
98,NaN,2-s2.0-37149016435,BIOC,1300,"Biochemistry, Genetics and Molecular Biology (..."
99,NaN,2-s2.0-37149052523,COMP,1700,Computer Science (all)

In [26]:
# create csv file from data frame

df.to_csv('gr3_86_07.csv')